feat: review if lint exist

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,5 +1,5 @@
-name: "Vite CI"
-description: "Realiza el lint, build, test and coverage para proyectos con Vite"
+name: "React CI"
+description: "Realiza el lint, build, test and coverage"
 inputs:
   matrix_version:
     description: "matrix de pruebas node"
@@ -23,16 +23,23 @@ inputs:
 runs:
   using: "composite"
   steps:
-    - name: Get package manager of Repo
+    - name: Get package manager and install command
       run: |
         if [ -f "yarn.lock" ]; then 
-          echo "name=yarn" >> $GITHUB_OUTPUT
+          echo "name=yarn" >> $GITHUB_OUTPUT 
+          echo "command=yarn --frozen-lockfile" >> $GITHUB_OUTPUT 
         elif [ -f "package-lock.json" ]; then 
           echo "name=npm" >> $GITHUB_OUTPUT 
+          echo "command=npm ci --no-progress --loglevel error" >> $GITHUB_OUTPUT 
         elif [ -f pnpm-lock.yaml ]; then 
           echo "name=pnpm" >> $GITHUB_OUTPUT 
+          echo "command=pnpm install --frozen-lockfile" >> $GITHUB_OUTPUT 
         else 
           echo "name=notfound" >> $GITHUB_OUTPUT  
+          echo "El código debe contener algún archivo de lockfile ('package-lock.json', 'yarn.lock' o 'pnpm-lock.yaml')."
+          echo "Asegurate de subirlo."
+          echo "ERROR: Falta archivo lockfile. Ver más en https://architecture-it.github.io/docs/Platform/Front/#manejo-de-dependencias"
+          exit 1
         fi
       id: package_manager
       shell: bash
@@ -55,33 +62,23 @@ runs:
       with:
         node-version: ${{ matrix.node-version }}
         cache: ${{ steps.package_manager.outputs.name }}
-    - name: config npmrc file fontawesome 
-      run: |
-        echo '@fortawesome:registry=https://npm.fontawesome.com/' >> .npmrc
-        echo '//npm.fontawesome.com/:_authToken=${{ inputs.fontawesome_token }}' >> .npmrc
-      shell: bash
-      if: ${{ inputs.fontawesome_token != '' }}
-    - name: config npmrc file github packages of company
-      run: |
-        echo '@customer-experience:registry=https://npm.pkg.github.com/' >> .npmrc
-        echo '@architecture-it:registry=https://npm.pkg.github.com/' >> .npmrc
-        echo '@operations-innovation:registry=https://npm.pkg.github.com/' >> .npmrc
-        echo '//npm.pkg.github.com/:_authToken=${{ inputs.packages_token }}' >> .npmrc
-      shell: bash
+    - name: Generate .npmrc file
+      uses: architecture-it/actions@generate-npmrc
+      with:
+        npm_token: ${{ inputs.packages_token }}
+        font_awesome_key: ${{ inputs.fontawesome_token }}
       if: ${{ inputs.packages_token != '' }}
     - name: Install dependencies
-      run: |
-        if [ -f yarn.lock ]; then 
-          yarn --frozen-lockfile
-        elif [ -f package-lock.json ]; then
-          npm ci --no-progress --loglevel error
-        elif [ -f pnpm-lock.yaml ]; then
-          pnpm install --frozen-lockfile
-        fi
+      run: ${{ steps.package_manager.outputs.command }}
       shell: bash
+    - name: Has lint script
+      run: echo "result=[[ $(cat package.json| jq .scripts.lint) != null ]]" >> $GITHUB_OUTPUT
+      shell: bash
+      id: has-lint-script
     - name: Lint
-      run: ${{ steps.package_manager.outputs.name }} run --if-present lint
+      run: ${{ steps.package_manager.outputs.name }} run lint
       shell: bash
+      if: ${{ steps.has-lint-script.outputs.result }}
     - name: Build
       run: ${{ steps.package_manager.outputs.name }} run build
       shell: bash
